version: "3.6"
services:
  web:
    image: mavishay/syncit-web-service:latest
    environment:
      - apiPath=http://api:3333
    ports:
      - '8080:4200'
  auth-service:
    image: mavishay/syncit-auth-service:latest
    ports:
      - '3334:3334'
    depends_on:
      - postgres
      - redis
    links:
      - "postgres:database"
      - "redis:redis"
  calendars-service:
    image: mavishay/syncit-calendars-service:latest
    ports:
      - '3335:3335'
    depends_on:
      - postgres
      - redis
    links:
      - "postgres:database"
      - "redis:redis"
  integrations-service:
    image: mavishay/syncit-integrations-service:latest
    ports:
      - '3336:3336'
    depends_on:
      - postgres
      - redis
    links:
      - "postgres:database"
      - "redis:redis"
  postgres:
    image: postgres:13
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "syncit"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:alpine"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - redis_persistence:/bitnami/redis/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data_persistence:/var/lib/rabbitmq/
      - rabbitmq_log_persistence:/var/log/rabbitmq

volumes:
  db_data:
  redis_persistence:
  rabbitmq_data_persistence:
  rabbitmq_log_persistence:

