apiVersion: v1
kind: ConfigMap
metadata:
  name: syncit-config
  labels:
    group: all
data:
  NEXT_PUBLIC_BETA: 'true'
  NEXT_PUBLIC_WEBAPP_URL: 'https://syncit.k8s.com'
  # - POSTGRES
  POSTGRES_DB: 'syncit'
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'postgres'

  # - RABBITMQ
  RABBITMQ_USER: 'guest'
  RABBITMQ_PASSWORD: 'guest'
  RABBITMQ_HOST: 'RABBITMQ:5672'
  RABBITMQ_QUEUE_NAME: 'events-watch'

  # - REDIS
  REDIS_HOST: 'redis'
  REDIS_PORT: '6379'

  SECRET: 'IvDidtHNwZ6erGdkGjGEFQ4KKWVm1Zntin'

  #   - GOOGLE CALENDAR/MEET/LOGIN
  GOOGLE_API_CREDENTIALS: '{"web":{"client_id":"876605967931-k68t49n0m0rim80cscmihq57b5tjr55q.apps.googleusercontent.com","project_id":"cal-com-349115","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"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","redirect_uris":["http://localhost/api/integrations/googlecalendar/callback"]}}'
