name: Unit-Test
on:
  pull_request_target:
    branches:
      - main
jobs:
  unit-test:
    strategy:
      matrix:
        node: ["14.x"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          # cache: "yarn"
          # cache-dependency-path: yarn.lock

      - name: Install deps
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Unit Test
        run: yarn test --codeCoverage --coverageReporters=json
        continue-on-error: false

      - name: Merge coverage reports
        run: jq -s '[.[]]|flatten' coverage/**/*.json &> coverage/coverage_report.json

      - name: Annotate Code Coverage Results
        uses: ataylorme/eslint-annotate-action@1.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "coverage/coverage_report.json"

      - name: Upload Coverage report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage-results
          path: coverage-results
